### ISSUE TITLE
我在22.04上部署项目使用该插件出现一下情况

### ISSUE THREAD

**Issue by leungyiuhoi** [Yanyutin753/googleSearch-On-Wechat#2]
微信用提问词，机器人回复：Request failed with status code: 403
Response text: {"message":"Unauthorized.","statusCode":403}

**Comment by Yanyutin753** [comment]
没余额了 或者国内服务器

**Comment by guluahljj** [comment]
在微信上使用该插件进行”搜索“”搜图“时，不会出现响应，但是可以进行正常的聊天以及其他插件的使用。
日志上的提示为
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/channel/chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
  File "/app/channel/chat_channel.py", line 178, in _generate_reply
    e_context = PluginManager().emit_event(
  File "/app/plugins/plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/app/plugins/googleSearch-On-Wechat/GoogleSearch.py", line 47, in on_handle_context
    self.handle_image_search(e_context, content[len("搜图 "):])
  File "/app/plugins/googleSearch-On-Wechat/GoogleSearch.py", line 97, in handle_image_search
    response = requests.request("POST", url, headers=headers, data=payload)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    self.putheader(header, value)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 313, in putheader
    super().putheader(header, *values)
  File "/usr/local/lib/python3.10/http/client.py", line 1256, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)
```
机器情况：阿里云服务器，国内的，Ubuntu22.04

**Comment by Yanyutin753** [comment]
国内服务器可能得需要代理
